title: Miftahul Jannat Mokarrama
logo: IMG_20211218_124453_Bokeh.jpg
description: “The simple things are also the most extraordinary things, and only the wise can see them.” - Paulo Coelho 
show_downloads: false
theme: jekyll-theme-minimal
